services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    trilobit_contao_ifthenelse.listener.insert_tags:
        class: Trilobit\IfthenelseBundle\EventListener\InsertTagsListener
        public: true
